"""added username

Revision ID: 291605870d6d
Revises: ffca1e0a9db0
Create Date: 2024-03-17 16:53:24.403014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291605870d6d'
down_revision = 'ffca1e0a9db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
